export const colors = [
  ["gray", "z"],
  ["slate", "s"],
  ["tomato", "e"],
  ["red", "r"],
  ["ruby", "f"],
  ["crimson", "w"],
  ["pink", "q"],
  ["plum", "u"],
  ["purple", "p"],
  ["violet", "v"],
  ["iris", "h"],
  ["indigo", "i"],
  ["blue", "b"],
  ["cyan", "c"],
  ["teal", "t"],
  ["jade", "j"],
  ["green", "g"],
  ["bronze", "n"],
  ["gold", "x"],
  ["brown", "d"],
  ["orange", "o"],
  ["amber", "a"],
  ["yellow", "y"],
  ["lime", "l"],
  ["mint", "m"],
  ["sky", "k"],
] as const;
